### ISSUE TITLE
Latest IntelliJ version is not supported

### ISSUE THREAD

**Issue by Blarc** [kcl-lang/intellij-kcl#27]
I am using IntelliJ IDEA 2024.1 (Ultimate Edition)
`Build #IU-241.14494.240, built on March 28, 2024.`

When I try to install the plugin, I get the following error:
![image](https://github.com/kcl-lang/intellij-kcl/assets/36704759/b6de02b3-9fc7-473d-b2c6-5f89c225cedb)

You can comment out the line: https://github.com/kcl-lang/intellij-kcl/blob/main/gradle.properties#L11C1-L11C25 and this way support all future versions.

**Comment by He1pa** [comment]
Hi, thanks for your contribution. But Im not sure it will be work, when I comment out the line
```
#pluginUntilBuild = .*
```
and
```
// untilBuild = properties("pluginUntilBuild")
```

I build the extension and publish it to marketplace,  It still compatibility with 233.*.
![image](https://github.com/kcl-lang/intellij-kcl/assets/56333845/1ab58b3b-404d-49a4-8c22-e25ebf292923)

I check the doc, also said `233.*` is the maximum version
> https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#build-number-validity

Can you give me more info about it.

**Comment by Blarc** [comment]
Hey,

sorry, it seems this setting is a bit confusing. Apparently, you also need to set: 
`updateSinceUntilBuild.set(false)` in `build.gradle.kts` (like [this](https://github.com/Blarc/ai-commits-intellij-plugin/blob/da73e4450c62059f80937c979b3ead82ea3e31ee/build.gradle.kts#L27C1-L27C37))
I found a comment on IntelliJ support that explains this: [link](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010590059/comments/4407033276562).

**Comment by He1pa** [comment]
> Hey,
> 
> sorry, it seems this setting is a bit confusing. Apparently, you also need to set: `updateSinceUntilBuild.set(false)` in `build.gradle.kts` (like [this](https://github.com/Blarc/ai-commits-intellij-plugin/blob/da73e4450c62059f80937c979b3ead82ea3e31ee/build.gradle.kts#L27C1-L27C37)) I found a comment on IntelliJ support that explains this: [link](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010590059/comments/4407033276562).
> 
> If you'd like I can open PR.

thanks, welcome for your PR. You forgot to remove this last time. You can solve it together in this PR
```
// untilBuild = properties("pluginUntilBuild")
```
